### ISSUE TITLE
Use the `atom-text-editor` tag instead of the `editor` class.

### ISSUE THREAD

**Issue by ButchDean** [Nidre/VS2015-Dark-Atom#1]
In index.less: Use the `atom-text-editor` tag instead of the `editor` class.

**Comment by Ludomancer** [comment]
Can you explain why?

When I apply the change you've mentioned, it does not work anymore.

**Comment by ButchDean** [comment]
Just reproduced it. When I install and select the theme I have a notification of two deprecations I have reported (with this being one of them).

I'm using Xubuntu. The options I am using are:

UI Theme: Atom Dark
Syntax Theme: Visual Studio 2015 Dark Theme
Atom Version: 1.0.2

**Comment by Ludomancer** [comment]
Fixed with 1.1.0, https://github.com/Nidre/VS2015-Dark-Atom/releases/tag/v1.1.0

Thanks for letting me know.
