### ISSUE TITLE
Target the selector `:host, atom-text-editor` instead of `.editor` for shadow DOM support.

### ISSUE THREAD

**Issue by ButchDean** [Nidre/VS2015-Dark-Atom#2]
In index.less: Target the selector `:host, atom-text-editor` instead of `.editor` for shadow DOM support.

**Comment by Ludomancer** [comment]
Sounds like the same suggestion as your first post. Could you elaborate? https://github.com/Nidre/VS2015-Dark-Atom/issues/1

**Comment by ButchDean** [comment]
Sure, the reason is exactly the same as [here](https://github.com/Nidre/VS2015-Dark-Atom/issues/1#issuecomment-127123157).

**Comment by Ludomancer** [comment]
Fixed with 1.1.0, https://github.com/Nidre/VS2015-Dark-Atom/releases/tag/v1.1.0

Thanks for letting me know.

**Comment by ButchDean** [comment]
No problem at all.
