### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by mamarilmanson** [Nidre/VS2015-Dark-Atom#5]
Hello... I just modified the code .less manually... and changed most of the sky blue to #559cd6 which is more of what I saw when I worked on visual studio code... :)

**Comment by Ludomancer** [comment]
@mamarilmanson 

Which colors you've modified exactly? I've taken all of the colors from the Visual Studio itself by copying the color codes. I might've missed some, let me knows were the faulty ones so I can take a look at and update ;)

**Comment by Ludomancer** [comment]
@mamarilmanson 

Seems like I've got some of the colors from VS Code instead of Visual Studio. You are tight about the blue color. I will push a new update soon ;)
